### ISSUE TITLE
Supprimer les process terminés.

### ISSUE THREAD

**Issue by MaximeCheramy** [TacOS-team/tacos#160]
Actuellement on les garde tous en mémoire inutilement.

**Comment by MaximeCheramy** [comment]
Vu que maintenant l'ordo est executé au retour du syscall sys_exit, j'ai l'impression que ce ticket ne pose plus de problème. Tu confirmes ?

**Comment by NicolasFloquet** [comment]
Il a jamais posé de vrai problème, l'idée était surtout de ne pas garder une liste de processus morts non? Je sais pas c'est toi qui l'a créé
