### ISSUE TITLE
Optimiser certains bouts de la libc

### ISSUE THREAD

**Issue by MaximeCheramy** [TacOS-team/tacos#171]
Cette histoire de loop remplacée par un appel à memset m'a fait réfléchir : ok, un memset est sans doute optimisé au mieux et au pire on ajoute qu'un appel de fonction donc c'est une bonne chose. Et du coup je me suis dit : oui mais notre memset, lui, il n'est certainement pas optimisé... Et effectivement, notre memset fait des affectations octets par octets alors qu'il pourrait le faire par morceaux de 32 bits.

Bien que le code résultat soit particulièrement simple, ce serait pas mal d'optimiser. Et par la même occasion, on pourrait essayer d'optimiser d'autres fonctions, en commençant en priorité par les fonctions les plus utilisées.

**Comment by NicolasFloquet** [comment]
Faudrait lister les fonctions que l'on pourrait potentiellement optimiser pour voir le reste à faire.

**Comment by MaximeCheramy** [comment]
Je vois pas trop ce qu'il reste à améliorer, le ticket est devenu trop vague. +1 pour la liste des fonctions, sinon on ferme.
