### ISSUE TITLE
exec_sighandler jardine la mémoire

### ISSUE THREAD

**Issue by NicolasFloquet** [TacOS-team/tacos#190]
Bug critique/majeur

Par moment, la fonction exec_sighandler va écrire un peu n'importe où.
Chez moi j'ai constaté que sigframe* frame pointe vers une zone de mémoire assez aléatoire, et la méthode fini par écraser stdin, ce qui provoque un crash à la prochaine utilisation de stdin.

**Comment by MaximeCheramy** [comment]
Je n'arrive plus à reproduire.
