### ISSUE TITLE
Gestion du CWD en espace kernel

### ISSUE THREAD

**Issue by MaximeCheramy** [TacOS-team/tacos#203]
Au lieu de gérer le chemin courant dans la libc, ce serait sans doute mieux de le gérer côté kernel. L'intérêt est principalement d'un point de vue simplification du code : plus besoin de tester dans chaque fonction de la libc s'il s'agit d'un chemin absolu ou relatif. On laisserait le VFS se débrouiller de manière centrale.

En terme d'implémentation, c'est un champ à rajouter dans le process qui serait exposé dans /proc/self/cwd (évite de rajouter un syscall pour ça).

**Comment by NicolasFloquet** [comment]
ça me parait élégant comme idée, par contre je suis pas certain de la façon dont on peut éviter un débordement de tampon dans le noyau avec ça, même si la sécurité est pas la priorité n°1 de tacos pour le moment :)

**Comment by MaximeCheramy** [comment]
Je trouve assez classe de pouvoir faire :

    ls -l /proc/self/cwd

**Comment by MaximeCheramy** [comment]
En fait j'ai oublié de faire la gestion des chemins relatifs au niveau du VFS. Je réouvre donc.
