### ISSUE TITLE
Refactoring de create_process

### ISSUE THREAD

**Issue by NicolasFloquet** [TacOS-team/tacos#204]
Actuellement on a deux implémentations de create_process, une pour un process à partir d'un elf, l'autre pour un process kernel. C'est crade.

**Comment by MaximeCheramy** [comment]
Ouais, il y a une grosse redondance de code, c'est assez pénible. Genre lorsqu'on veut rajouter un truc faut pas oublier l'autre. C'est vraiment nécessaire.

**Comment by NicolasFloquet** [comment]
Je viens de faire la factorisation rapidement en mettant des if(elf) là où il faut, il y en a pas tant que ça, et ils peuvent tous être réglés par une utilisation plus intelligente du process_init_data_t
Par ailleurs, j'ai trouvé quelques bugs potentiels probablement issus de la duplication du code, donc ça va effectivement faire du bien je pense.

**Comment by MaximeCheramy** [comment]
Et tu penses commiter ta factorisation ? :)

**Comment by NicolasFloquet** [comment]
Evidemment! Mais je suis pas en vacances, ni chercheur :D

**Comment by MaximeCheramy** [comment]
ref #23

**Comment by MaximeCheramy** [comment]
Tu penseras à réactiver le hook pour git. Tu as ajouté des warnings.

**Comment by NicolasFloquet** [comment]
Effectivement, désolé ^^
