### ISSUE TITLE
[XXX kernel.c:82] avoid segment_not_present

### ISSUE THREAD

**Issue by NicolasFloquet** [TacOS-team/tacos#216]
Un petit morceau de code qui a l'air de contourner un problème qu'on ne maitrise pas, ça mériterais de se pencher dessus.

**Comment by MaximeCheramy** [comment]
Pour info, on peut le virer et ça continue à marcher sous bochs et qemu.

**Comment by NicolasFloquet** [comment]
Effectivement ça vallait le coût de tester :p
