### ISSUE TITLE
Supprimer code inutilisé

### ISSUE THREAD

**Issue by MaximeCheramy** [TacOS-team/tacos#221]
Il y a dans TacOS du code qui n'est malheureusement plus utilisé. Il faudrait faire le tour et voir ce qu'on peut dégager.

**Comment by MaximeCheramy** [comment]
Quelqu'un utilise heap ? On l'avait créé dans quel but ?

**Comment by MaximeCheramy** [comment]
mbr.c n'est pas compilé.

**Comment by NicolasFloquet** [comment]
mbr est en cours de refactoring pour avoir un interêt, et heap effectivement ne sert à rien

**Comment by MaximeCheramy** [comment]
Penser à make clean en cas de problème de compilation.

**Comment by MaximeCheramy** [comment]
J'avais oublié que je l'avais supprimé lorsque j'ai eu besoin d'un heap pour les events... Du coup je l'ai recodé : https://github.com/TacOS-team/tacos/blob/master/kernel/utils/heap.c

**Comment by MaximeCheramy** [comment]
Ticket pas assez précis, je ferme.
