### ISSUE TITLE
Nettoyage de l'arborescence

### ISSUE THREAD

**Issue by NicolasFloquet** [TacOS-team/tacos#222]
Je regardais un peu tous les répertoires à la racine du projet, et je me suis dit que c'était n'imp.
- /include => j'ai aucune idée de ce que c'est sensé contenir
- /libc => devrait aller dans /libs
- /system => devrait être mergé avec /lib/tacos
- /tests => wtf?

**Comment by MaximeCheramy** [comment]
/include => Ce sont les include des trucs du kernel directement utilisés par des applications. Pour la libc on avait le même problème : on a choisit de dupliquer les .h.
/libc = > Effectivement /libs est récent, il pourrait bouger.
/system => pourquoi pas
/tests => Ce sont les tests de la lib std c++. Je sais pas trop quoi en faire. Les laisser là ?

**Comment by NicolasFloquet** [comment]
/include => si c'est des includes propres à tacos, ça devrait faire partie de la libtacos, sinon c'est que c'est mal foutu
/test => dans applications, comme test_io

**Comment by MaximeCheramy** [comment]
/tests => ok pour mettre dans applications par contre actuellement c'est fait pour tourner en dehors de tacos...
